pool:
  name: 'Devpool'

stages:
- stage: Deploy
  jobs:
  - job: DeployMongoDB
    displayName: 'Deploy MongoDB to Kubernetes Namespace three-tier'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        #azureSubscription: 'k8s connection'
        kubernetesServiceEndpoint: 'k8s connection'
        azureResourceGroup: 'dev-env'
        kubernetesCluster: 'dev-cluster'
        namespace: 'three-tier'
        command: 'apply'
        arguments: '-f DB/database.yml'
      displayName: 'Deploy MongoDB to Kubernetes'
      